CREATE TABLE `inventory_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`referencia` varchar(64) NOT NULL,
	`descripcion` text,
	`parteFabricante` varchar(128),
	`stockActual` double DEFAULT 0,
	`costoUnitario` double DEFAULT 0,
	`totalStock` double DEFAULT 0,
	`cuenta` varchar(64),
	`puntoPedido` double DEFAULT 0,
	`minimo` double DEFAULT 0,
	`maximo` double DEFAULT 0,
	`umEmision` varchar(16),
	`claseAbc` varchar(4),
	`usoAnno` double DEFAULT 0,
	`usoAnnoAnt` double DEFAULT 0,
	`leadTimeProm` double DEFAULT 0,
	`rotacionAnno` double DEFAULT 0,
	`rotacionAnt` double DEFAULT 0,
	`quiebresAnno` double DEFAULT 0,
	`quiebresAnt` double DEFAULT 0,
	`costoPromedio` double DEFAULT 0,
	`ultimoCosto` double DEFAULT 0,
	`nitProveedor` varchar(32),
	`bodega` varchar(32),
	`proveedor` text,
	`consumoAnual` double DEFAULT 0,
	`consumoDiario` double DEFAULT 0,
	`leadTimeDias` double DEFAULT 0,
	`stockSeguridad` double DEFAULT 0,
	`puntoReorden` double DEFAULT 0,
	`inventarioDias` double DEFAULT 0,
	`estado` varchar(32),
	`accionRequerida` varchar(64),
	`cantidadAPedir` double DEFAULT 0,
	`valorAPedir` double DEFAULT 0,
	`prioridad` varchar(16),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `inventory_items_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `purchase_orders` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ordenCompra` varchar(32),
	`descripcion` text,
	`qtyOrdenada` double DEFAULT 0,
	`um` varchar(16),
	`qtyRecibida` double DEFAULT 0,
	`qtyPendiente` double DEFAULT 0,
	`costoUnitario` double DEFAULT 0,
	`proveedor` text,
	`parteFabricante` varchar(128),
	`comprador` varchar(128),
	`mainsaver` varchar(64),
	`fechaPromesa` timestamp,
	`fechaRequerida` timestamp,
	`valorImpuesto` double DEFAULT 0,
	`valorPendiente` double DEFAULT 0,
	`diasRetraso` int DEFAULT 0,
	`estado` varchar(32),
	`cumplimiento` double DEFAULT 0,
	`prioridad` varchar(16),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `purchase_orders_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `suppliers` (
	`id` int AUTO_INCREMENT NOT NULL,
	`nit` varchar(32) NOT NULL,
	`nombre` text,
	`tipoImpuesto` varchar(16),
	`email` varchar(320),
	`telefono` varchar(32),
	`contacto` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `suppliers_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `sync_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`syncType` varchar(32) NOT NULL,
	`status` varchar(16) NOT NULL,
	`itemsProcessed` int DEFAULT 0,
	`ordersProcessed` int DEFAULT 0,
	`suppliersProcessed` int DEFAULT 0,
	`errorMessage` text,
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	CONSTRAINT `sync_logs_id` PRIMARY KEY(`id`)
);
