CREATE TABLE IF NOT EXISTS `facturacion_oc` (
  `id` int AUTO_INCREMENT NOT NULL,
  `fechaEntrega` varchar(32),
  `fechaOC` varchar(32),
  `bodega` varchar(16),
  `referencia` varchar(64),
  `item` varchar(16),
  `moneda` varchar(8),
  `descItem` text,
  `um` varchar(16),
  `cantidad` double DEFAULT 0,
  `precioUnit` double DEFAULT 0,
  `valorImptos` double DEFAULT 0,
  `valorSubtotal` double DEFAULT 0,
  `valorNeto` double DEFAULT 0,
  `documento` varchar(64),
  `proveedor` text,
  `doctoSolicitud` varchar(64),
  `doctoOrden` varchar(64),
  `referenciaOC` varchar(64),
  `comprador` varchar(128),
  `estado` varchar(32),
  `fecha` varchar(32),
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `facturacion_oc_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `facturacion_ocs` (
  `id` int AUTO_INCREMENT NOT NULL,
  `referencia` varchar(64),
  `notasDocto` text,
  `co` varchar(16),
  `nroDocto` varchar(32),
  `fecha` varchar(32),
  `estado` varchar(32),
  `nroFactura` varchar(64),
  `razonSocial` text,
  `descServicio` text,
  `moneda` varchar(8),
  `valorBruto` double DEFAULT 0,
  `valorDescuentos` double DEFAULT 0,
  `subtotal` double DEFAULT 0,
  `valorImpuestos` double DEFAULT 0,
  `valorNeto` double DEFAULT 0,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  CONSTRAINT `facturacion_ocs_id` PRIMARY KEY(`id`)
);
